 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain_flant5xl
  load_finetuned: False

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xl.pth"
  finetuned: ""

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp32"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # T5
  t5_model: "/13390024681/3D/3D-LLM/model_zoo/flant5-xl" # /13390024681/3D/3D-LLM/model_zoo/flant5-xl

  # generation configs
  prompt: ""

  encoder_ckpt_path: "/13390024681/LLaVA/model_zoo/vdetr/checkpoint_best_73.pth"
  


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
